### ISSUE TITLE
What benefits are multi-module setups giving us

### ISSUE THREAD

**Issue by wenns** [wenns/sonar-cxx#367]
Now that Im fiddling with the multi module stuff again, I have a silly question: 

*Which benefits does a multi-module setup giving me? As a SonarQube / C++ Community Plugin user, why and when should I use this feature?*

Summarizing the discussion:

**Drawbacks**
* using multi-modules complicates your setup

**Benefits**
* using multi-modules gives the possibility to redefine parts of the setup for parts of the project. This is important in situations like:
  - You want to deal with big (and maybe old&rusty) projects consisting of many parts with lots of different include paths / defines etc. 
  - You're using tools like visual studio bootstrapper, which creates a multi-module setup for you

**Comment by jmecosta** [comment]
i completely agree with you, and i dont use multi module. since it indeed
makes it more complex to setup. however for windows users and likely when
running in visual studio boot strapper this is the default behavior. i come
across this issue because we have in most of our projects a mix of c# and
c++ code. the obvious was to use the visual studio boot strapper so that we
dont have actually any configuration to set. the issue here is that by
default the boot strapper creates multi modules so any of reports created
for c++ would need to be moved to each submodule to still use the same
settings. therefore the need to be able to access the reports from the
project root dir.

in my case to able to import all languages i had to disable all boot
strapper, to still use the same setup and import all lanaguages.

beneficts: i dont see that many apart from the fact you can have different
settings for each module as you said

**Comment by jmecosta** [comment]
and @Bertk was doing something to improve the bootstrapper to take out the include and defines from visual studio projects and pass to each module, so that would actually simplify the setup. and make the analysis faster also. i even thing there is no other way to go for visual studio users, as a example we started using native nuget packages and its impossible to me to keep include directories defined in sonar.project settings because those are always changing. so i will need to move shortly to the bootstrapper so that we feed those ones automatically

**Comment by guwirth** [comment]
> likely when running in visual studio boot strapper 

Is the visual studio boot strapper also working for C++ with the cxx plugin?

> mix of c# and c++ code

Means multi-language projects?

We also don't use it. But my understanding is that it could be useful to analyze each visual studio project (.vcxproj) independent in a big code base to extract the settings, especially the defines and includes on project level (VS project=module). You can do this with one SQ project in the root.

Up to know we do this different by creating independent SQ projects for each VS project with always an own configuration in the root folder of the VS project.

Don't know what is in future better or have more advantages disadvantage?
Looking also forward to get some hints.

@jmecosta you use it because c# bootstrapper is using it and you like to setup multi-language projects? Right?

**Comment by jmecosta** [comment]
Yep should handle c++ JavaScript c# vb and a few more. Its easily
extendable. What it will not do is extract the settings for the cxx
plugin   as it would compete with the commercial plugin. And yes we are
already using multi language for a bit of time now. We have our own
msbuild  + c# + c++ + xaml. That's our typical setup

**Comment by guwirth** [comment]
And how do you merge the different settings of C#, C++, ... in the configuration files? Manually or is this somehow automated?

**Comment by jmecosta** [comment]
Manually now, because the boot strapper still has a few issue in our
environment so we tend to disable it. C++ only now we started having issues
because we introduced nuget packages. So we might need to come up with
something fast to automate the settings for c++. C# is not a big issue
because there are not that many settings. But this is really not optimal
and would be great to have a tool that does that all for you. I might
actually create something this to support this has I understand the boot
strapper might be written in c# soon

**Comment by wenns** [comment]
FYI: experimenting with multi-module I found out that the xunit's 'simple' mode isnt compatible with multi-module setting: the metric values is assigned to the module and then aggregated at the project level. Which makes it wrong then...

**Comment by jmecosta** [comment]
Is that a issue of the platform?

**Comment by wenns** [comment]
No, is not. Example: 

given project P containing modules M1 and M2 and an xunit.xml containig 10 testcases.
In multi-module setting, the analysis runs for M1, M2 and P. (with your recent PR) xunit.xml is processed in context of M1 aund M2. Each time the plugins counts the testcases and assignes them to the project (in this case: M1 and M2). The platform aggregates them at P. Result: 20 testcases.

Hope that was understandable...

**Comment by jmecosta** [comment]
ok, found the way to solve this. and the answer to one of your questions. what is the isReactorProject..

so see:
http://jira.codehaus.org/browse/SONARNTEST-14

and the corresponding way to fix this:
https://github.com/SonarCommunity/sonar-dotnet-tests-library/pull/4/files

so we should only run the xunit sensor once for top project. for the others we can do the same?

**Comment by guwirth** [comment]
Linked to #358

**Comment by jmecosta** [comment]
https://github.com/wenns/sonar-cxx/wiki/Path-and-path-separator-issues/0f5a9b5c9aaaecbe8a18823667e50a6737e252e4
https://github.com/wenns/sonar-cxx/wiki/Path-and-path-separator-issues/cef352f7c1099d64787a0d812a91a665a10c54df
