### ISSUE TITLE
C++ Community / (2) Codananalysis / Add Value

### ISSUE THREAD

**Issue by guwirth** [wenns/sonar-cxx#383]
Using 'Add Value' button in the configuration UI there is more then one external rule field added. Seems first time 2, then 3, ... .

(minor bug)

**Comment by jmecosta** [comment]
not sure we can do anything about it... has this seems to be a bug in the platform?

**Comment by wenns** [comment]
Are you sure you're using it properly?

**Comment by jmecosta** [comment]
Duno have to check...  The thing at that point was that it was not even recommended to define rules as we have now. The recomended way was to only use template rules since those sonar can track history. So maybe we can for this ticket drop those xmls in ui and instead provide a tool to upload those profiles. I was already planning to migrate the cpplint ones for myself. Another useful thing on doing so is that it will be possible to then define technical debt for those rules also which currently we cannot. 


If you are OK with this is can the prepare the necessary tools.

**Comment by guwirth** [comment]
* What exactly would the tool do? Read the XML and create a ... ?
* Would this be an external tool or somehow build in?
* Would the tool / sources be part of the cxx plugin?

**Comment by jmecosta** [comment]
The tool, a python script that would be kept in the helpers section of the
repository would read the current XML we have defined in ui and just create
the rules. I don't think its needed to enable the rules in a given profile
beacuase its up to user to enable those in each profile. To ease the
transition it would be recommended to backup the current profile, create
the rules and the restore the profile so everything is enabled

**Comment by jmecosta** [comment]
another reason for this, is that the plaftorm is on the way to deprecate xml importer stuff so we might need to react to this also.

**Comment by guwirth** [comment]
> recomended way was to only use template rules 

Still don't understand what template rules are? Is there an example?

**Comment by jmecosta** [comment]
Sure, some of the checks we have in the ast module are template rules. So
you create a new rule based on a template with different parameters . we
have already template rules for all sensors. You can search for them using
the rules service in the web ui.

The advantage is if for example when upgrading a sonar instance you don't
loose any of the rules because you forgot to update the XML in the web ui.
Because those ones persist with the profiles

**Comment by guwirth** [comment]
But what would your script doing? Create automatic Java code?
From some static code analyzer I have 2500 rules. Isn't that too much?

**Comment by jmecosta** [comment]
It  would just pickup the XML you have in ui and use the rest api to create
the rules. This is for transition after that the recommended way is to use
the web ui.

**Comment by guwirth** [comment]
@jmecosta what should we do with this bug?

**Comment by jmecosta** [comment]
Its not a bug from the plugin, ive seen this with other properties. If you set the exclusions on the sonar web you will see duplicated things showing up. For me this can be closed
