### ISSUE TITLE
The dependency analyzer extends projects scope by pulling the dependencies into it

### ISSUE THREAD

**Issue by wenns** [wenns/sonar-cxx#405]
The bug can be observed when analysing "test/resources/org/sonar/plugins/cxx/include-directories-project". "sonar.sources" is set to "src". Nevertheless, the dependency analyser pulls "include" and "include_snd" into SQ, resulting in files=10 (should be: 1). Ouch...

**Comment by wenns** [comment]
@typz: Can you have a look, please? I've tried a fix but earned a NullPointerException. See the branch 'dependency_analyzer_bug'. It also includes a behave test which triggers the bug.

**Comment by Typz** [comment]
I will try to check this before the weekend.

**Comment by Typz** [comment]
Issue is in DsmSerializer.serializeCell(), where "dependencyIndex.get(cell.getEdge())" can now return null (and thus get us a NullPointerException).

It is easy to fix there, and it makes the test pass; however I am not sure this is sufficient: we may still end up importing the file somehow (since they will get in the serialized DSM: just now without the dependency).

A complete fix would be to "simply" filter the whole packages and files graphs at the beginning of save(), to ensure we don't introduce the extra files in any place [neither in saved deps, feedback cycles, or DSM]... Filtering in addFile() would be much simpler (e.g. one test in line 108), but I am not sure the included files have been indexed yet...

I'll keep looking...

**Comment by wenns** [comment]
Thanks for poking. FYI: dependency analysis runs as part of the Squid sensor, which is *after* indexing files.

**Comment by Typz** [comment]
Well that's cool, should allow for a nice and clean fix. I'll try that.

**Comment by Typz** [comment]
Updated the branch 'dependency_analyzer_bug' with a working patch.
I have an issue with the smoketest though: the multiple include rule is somehow not activated, so extra warning is generated instead...

**Comment by wenns** [comment]
Cool, thanks. Extra warning: will have a look.

**Comment by guwirth** [comment]
@Typz Could you provide a solution by 2015-04-19 for this? If not we remove it from 0.9.3.

**Comment by Typz** [comment]
The branch was merged by @wenns some times ago, it should be fine I believe.
