### ISSUE TITLE
Intel Inspector XE integration does not show all reported issues

### ISSUE THREAD

**Issue by hfufu** [wenns/sonar-cxx#466]
I'm a confused with the Intel Inspector XE integration report integration mentioned in https://github.com/wenns/sonar-cxx/wiki/Extending-the-code-analysis. For project that make use of 3rd party library and issue like memory leak or invalid reference, the reported problem location is somewhere inside the 3rd-party library. For example, if i call getHandle() provided by the 3rd-party lib, but forget to call releaseHandle(), then the reported memory leak location is in the 3rd-party lib instead   of my code.

When the sonar project properties are configured to exclude the 3rd-party code (or simply the 3rd party code is not available at all), the memory leak problem will not show up in the result sonar report at all, simply because the inspector reported problem location is outside the analysis cpp source set. 

Is there a way to make the reported issues show up as is in sonar report even the problem is "outside" the source code location? 

Also the intelInspectorReport_2_cppcheckReport.py does not convert any call stack info. I look into the py file and think it is possibile to customize the problem title to add some extra information like a callstack, but it would not be very readable to put something like a call stack in the problem title. Is there any proper way to add extra information via the otherReportPath facility?

**Comment by jmecosta** [comment]
This is a limitation of sonar, you can only create issues against valid
resources in sonar.
we found it more usefull it include the test that raises that, and not that
much the stacktrace since devs will need to run intel inxpector anyway to
fix the problem. But anyway the provided script is just a small example,
you can extend it in anyway you want to contain any information you want, i
can see the value of the stacktrace.

If you use MSBuild, you can try
https://github.com/jmecosta/MSBuild-SonarQube-CXX/tree/master/InspectorTask.
I can push a update that you can create a nuget package and hook it up to
the build. the python script in this case is not needed

**Comment by guwirth** [comment]
@hfufu can we close this?

**Comment by guwirth** [comment]
I close this. Please reopen if still an issue.
