### ISSUE TITLE
Use sonar-cxx for analyzing c code.

### ISSUE THREAD

**Issue by gusbremri** [wenns/sonar-cxx#657]
Hello,

Is this pluggin useful for c code as-well? Or is it better to avoid.

Best Regards
gusbremri

**Comment by guwirth** [comment]
@gusbremri The plugin is mainly a C++ plugin. But you can try also to parse your C code with the additional setting ```sonar.cxx.cFilesPatterns```. I know that some others are already using it for their C code base. Because most reports are only imported from external tools the quality of the results depends mainly on this tools and less on the plugin.
